version: '3.8'

services:
  my-app:
    build: .
    container_name: my-app
    volumes:
      - ./users_books.db:/tmp/users_books.db
    environment:
      - DATABASE_URL=postgresql://postgres:covdeP-higtup-mimgi7%40@db.krtkebdtxypgczlamacx.supabase.co:5432/postgres

    ports:
      - "5050:5000"

