version: '3.8'

services:
  my-app:
    build: .
    container_name: my-app
    volumes:
      - ./users_books.db:/tmp/users_books.db
    environment:
      - DATABASE_URL=sqlite:////tmp/users_books.db
    ports:
      - "5050:5000"

