services:
  - type: web
    name: hostbook-bot
    env: python
    # Явно отключаем Docker (если файл есть в репозитории)
    dockerfilePath: ""  # Пустая строка = игнорировать Dockerfile
    
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hosthing:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://hostbooktinder.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
      # PORT можно удалить (Render автоматически подставляет $PORT)
    
    healthCheckPath: /
    plan: free